.openshift/

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -29,11 +29,11 @@ then
   # 
   if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
   then
-      echo 1>&2
-      echo "Could not find mysql database. Please run:" 1>&2
-      echo "rhc cartridge add mysql -a $OPENSHIFT_APP_NAME" 1>&2
-      echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
-      echo 1>&2
+    echo 1>&2
+    echo "Could not find mysql database. Please run:" 1>&2
+    echo "rhc cartridge add mysql -a $OPENSHIFT_APP_NAME" 1>&2
+    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+    echo 1>&2
   fi
 
   if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
